[project]
name = "pokemon"
version = "0.1.0"
description = "Pokemon MCP Server with FastMCP Clients"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "mcp[cli]>=1.6.0",
    "fastmcp>=2.0.0",
    "httpx>=0.25.0",
]
